version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "tamiroh"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      reviewers:
          - "tamiroh"
