name: Label Checker
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - labeled
            - unlabeled
permissions: {}
jobs:
    check-version-labels:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            pull-requests: read
        steps:
            - uses: docker://agilepathway/pull-request-label-checker:v1.6.115@sha256:253c71fe97d6ae19fff21608f1e10493ec322e7c95d4fed4695b2b8d11f58fb2
              with:
                  one_of: major,minor,patch
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
    check-category-labels:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            pull-requests: read
        steps:
            - uses: docker://agilepathway/pull-request-label-checker:v1.6.115@sha256:253c71fe97d6ae19fff21608f1e10493ec322e7c95d4fed4695b2b8d11f58fb2
              with:
                  one_of: feature,enhancement,bug,dependencies,chore
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
