name: Label Checker
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - labeled
            - unlabeled
permissions: {}
jobs:
    check-version-labels:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
                  sparse-checkout: .github/actions
            - uses: ./.github/actions/require-one-label
              with:
                  one-of: major,minor,patch
    check-category-labels:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
                  sparse-checkout: .github/actions
            - uses: ./.github/actions/require-one-label
              with:
                  one-of: feature,enhancement,bug,dependencies,chore
