name: Label Checker
on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - labeled
            - unlabeled
jobs:
    check-version-labels:
        runs-on: ubuntu-latest
        steps:
            - uses: docker://agilepathway/pull-request-label-checker:latest
              with:
                  one_of: major,minor,patch
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
    check-category-labels:
        runs-on: ubuntu-latest
        steps:
            - uses: docker://agilepathway/pull-request-label-checker:latest
              with:
                  one_of: feature,enhancement,bug,dependencies,chore
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
