name: Auto Assign
on:
    pull_request:
        types: [opened, reopened]
permissions: {}
jobs:
    assign:
        if: github.event.pull_request.user.type != 'Bot'
        runs-on: ubuntu-latest
        timeout-minutes: 5
        permissions:
            pull-requests: write
        steps:
            - name: Assign the author
              env:
                  GH_TOKEN: ${{ github.token }}
                  GH_REPO: ${{ github.repository }}
                  PR_NUMBER: ${{ github.event.pull_request.number }}
                  AUTHOR: ${{ github.event.pull_request.user.login }}
              run: gh api --silent --method POST "repos/$GH_REPO/issues/$PR_NUMBER/assignees" -f "assignees[]=$AUTHOR"
