name: Test
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: npm install
            - name: Run ESLint
              run: npx eslint .
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: npm install
            - name: Run Prettier
              run: npx prettier --check .
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: npm install
            - name: Run build
              run: npm run build
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install modules
              run: npm install
            - name: Run unit tests
              run: npm run coverage
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
